### ISSUE TITLE
Plugin crashes Sanity Studio UI with new theming UI

### ISSUE THREAD

**Issue by patrulea** [sanity-io/sanity-plugin-markdown#90] opened 2023-12-20 16:47 UTC
Attempting to render the Markdown field causes the content tool UI to crash with a message that reads:  
`undefined is not an object (evaluating 'theme.sanity.color.selectable.primary')`

![image](https://github.com/sanity-io/sanity-plugin-markdown/assets/33817380/46854998-413c-499f-8380-1b492a1c1e22)

This is probably related to the new, undocumented theming API introduced in `sanity@3.23.0`, released yesterday (December 19, 2023).

* https://www.sanity.io/changelog/f75445eb-3c3e-4d1e-986d-71a61223aa83
* https://www.sanity.io/docs/theming

**Comment by blimey85** [comment] 2023-12-27 05:50
I'm getting this same issue. Were you able to find a solution?

**Comment by patrulea** [comment] 2023-12-27 14:03
I ended up not needing the plugin so I uninstalled it. But you can downgrade your Sanity version in the meantime.

**Comment by liznelson** [comment] 2023-12-28 23:50
Any recommendation on appropriate package versions would be helpful. I am hitting dependency issues left and right trying to find the best sanity configuration to keep using the markdown plugin.

**Comment by patrulea** [comment] 2023-12-29 16:28
In [their changelog](https://www.sanity.io/changelog/f75445eb-3c3e-4d1e-986d-71a61223aa83#935198d6ec1d) they recommend `v3.22.0`.

**Comment by manaskhandelwal** [comment] 2024-01-08 11:20
The issue is likely due to their transition to the new UI. 
I have created a pull request (#92) to fix this.

**Comment by drewlyton** [comment] 2024-01-10 19:58
> I have created a pull request (#92) to fix this.

Would love to see this get merged soon!

**Comment by pedrobonamin** [comment] 2024-01-15 08:01
Thanks for reporting, a fix is in progress and will be released in the new sanity version tomorrow.

**Comment by robinpyon** [comment] 2024-01-15 11:01
A new version of this plugin (`4.1.1`) has been released which correctly checks for the existence of `theme.sanity.color.selectable` before accessing, which will address this issue directly if you need a fix right now.

As mentioned above, the next Studio release will ensure the correct value is provided. The absence of `selectable` in the theme object was a recent regression. Thanks for your patience here.

**Comment by robinpyon** [comment] 2024-01-18 09:48
This should be fixed as of Sanity Studio [3.25.0](https://github.com/sanity-io/sanity/releases/tag/v3.25.0) – please shout if you're still seeing issues here!

**Closed by robinpyon** 2024-01-18 09:48 UTC
